title: MB's Blog
owner_name: Mihir Bapat
github_username: Hypernova101
github_repo: "MihirCSP" 
baseurl: "/MihirCSP"
future: true
remote_theme: jekyll/minima
minima:
  skin: dark
  social_links:
    - { platform: github, user_url: "https://github.com/Hypernova101"}
    - { platform: x, user_url: "https://x.com/NighthawkCoding/" }
    - { platform: youtube, user_url: "https://www.youtube.com/@nighthawkcodingsociety2868" } 
# remote_theme: pages-themes/midnight@v0.2.0
# remote_theme: pages-themes/cayman@v0.2.0
# remote_theme: pages-themes/dinky@v0.2.0
# remote_theme: pages-themes/minimal@v0.2.0
# remote_theme: pages-themes/time-machine@v0.2.0
# test commit
plugins:
  - jekyll-remote-theme
minima:
  nav_pages:
    - navigation/blog.md
    - navigation/search.md
    - navigation/about.md
    - navigation/cookieclicker.md
    - navigation/mcqblog.md
    - README4YML.md
